In [5]:
import pandas as pd 
data = {
    "players":["virat","rohith","sehwag","dhoni","virat","rohith","sehwag","dhoni"],
    "matches":[100,200,300,400,100,200,300,400],
    "runs":[154,200,123,145,257,309,198,128],
    "balls":[50,100,120,120,150,80,120,100]
}
ipl=pd.DataFrame(data)
ipl

  players  matches  runs  balls
0   virat      100   154     50
1  rohith      200   200    100
2  sehwag      300   123    120
3   dhoni      400   145    120
4   virat      100   257    150
5  rohith      200   309     80
6  sehwag      300   198    120
7   dhoni      400   128    100

In [6]:
ipl["strik_rate"]=(ipl["runs"]/ipl["balls"])*100
ipl

  players  matches  runs  balls  strik_rate
0   virat      100   154     50  308.000000
1  rohith      200   200    100  200.000000
2  sehwag      300   123    120  102.500000
3   dhoni      400   145    120  120.833333
4   virat      100   257    150  171.333333
5  rohith      200   309     80  386.250000
6  sehwag      300   198    120  165.000000
7   dhoni      400   128    100  128.000000

In [7]:
ipl=ipl.loc[(ipl["players"]=="virat")&(ipl["runs"]>150)]
ipl

  players  matches  runs  balls  strik_rate
0   virat      100   154     50  308.000000
4   virat      100   257    150  171.333333

In [10]:
grp=df.groupby("players")["runs"].sum()
print(grp)

players
dhoni     273
rohith    509
sehwag    321
virat     411
Name: runs, dtype: int64

In [12]:
grp=df.groupby(["players","matches"])["runs"].sum()
print(grp)

players  matches
dhoni    400        273
rohith   200        509
sehwag   300        321
virat    100        411
Name: runs, dtype: int64

In [21]:
summs=df.groupby("players").agg(
    Total_runs=("runs","sum"),
    average_runs=("runs","mean"),
    matches_played=("matches","sum"),
    highest_score=("runs","max"),
    lowest_score=("runs","min"),
    total_balls=("balls","sum"),
    fifties=("runs",lambda x:((x>=50) & (x<100)).sum())
)

summs

,Total_runs,average_runs,matches_played,highest_score,lowest_score,total_balls,fifties
players,,,,,,,
dhoni,273,136.5,800,145,128,220,0
rohith,509,254.5,400,309,200,180,0
sehwag,321,160.5,600,198,123,240,0
virat,411,205.5,200,257,154,200,0

In [21]:
import pandas as pd

data = {
    "Name":["Rahul","Joy","Kumar","Mahi","Jhanvi","Arjun"],
    "age":[25,35,44,21,28,45],
    "city":["Banglore","Pune","Kolkata","Mumbai","Chennai","Dehli"],
    "sal":[78000,25000,45000,12000,65000,50000],
    "Dep":["IT","HR","Finance","HR","IT","Finance"]
}

df = pd.DataFrame(data)

df

     Name  age      city    sal      Dep
0   Rahul   25  Banglore  78000       IT
1     Joy   35      Pune  25000       HR
2   Kumar   44   Kolkata  45000  Finance
3    Mahi   21    Mumbai  12000       HR
4  Jhanvi   28   Chennai  65000       IT
5   Arjun   45     Dehli  50000  Finance

In [22]:
salary=df["sal"]
salary

0    78000
1    25000
2    45000
3    12000
4    65000
5    50000
Name: sal, dtype: int64

In [23]:
dep=df['age']
dep.values

array([25, 35, 44, 21, 28, 45])

In [25]:
df[["Name","Dep","sal","age"]]

     Name      Dep    sal  age
0   Rahul       IT  78000   25
1     Joy       HR  25000   35
2   Kumar  Finance  45000   44
3    Mahi       HR  12000   21
4  Jhanvi       IT  65000   28
5   Arjun  Finance  50000   45

In [26]:
print(type(df["Name"]))
print(type(df[["Name"]]))

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

In [27]:
df.loc[:,["Name","sal"]]

     Name    sal
0   Rahul  78000
1     Joy  25000
2   Kumar  45000
3    Mahi  12000
4  Jhanvi  65000
5   Arjun  50000

In [29]:
df.iloc[:,2]
df.iloc[:,[1,4]]

   age      Dep
0   25       IT
1   35       HR
2   44  Finance
3   21       HR
4   28       IT
5   45  Finance

In [30]:
print(df.iloc[0:4])

    Name  age      city    sal      Dep
0  Rahul   25  Banglore  78000       IT
1    Joy   35      Pune  25000       HR
2  Kumar   44   Kolkata  45000  Finance
3   Mahi   21    Mumbai  12000       HR

In [32]:
print(df.iloc[[0,2,5]])

    Name  age      city    sal      Dep
0  Rahul   25  Banglore  78000       IT
2  Kumar   44   Kolkata  45000  Finance
5  Arjun   45     Dehli  50000  Finance

In [37]:
df.loc[0,"sal"]

np.int64(78000)

In [38]:
df.loc[0:3,"Name"]

0    Rahul
1      Joy
2    Kumar
3     Mahi
Name: Name, dtype: str

In [39]:
df.loc[0:3,["Name","age","Dep"]]

    Name  age      Dep
0  Rahul   25       IT
1    Joy   35       HR
2  Kumar   44  Finance
3   Mahi   21       HR

In [41]:
df.loc[0:3,["Name","age","Dep"]]
df.loc[df["age"]>25,["Name","sal","Dep"]]

     Name    sal      Dep
1     Joy  25000       HR
2   Kumar  45000  Finance
4  Jhanvi  65000       IT
5   Arjun  50000  Finance

In [45]:
df.query("age>25" and "sal>50000")

     Name  age      city    sal Dep
0   Rahul   25  Banglore  78000  IT
4  Jhanvi   28   Chennai  65000  IT

In [47]:
df.query("age>25 and sal>50000 and city in ['Banglore','Chennai']")

     Name  age     city    sal Dep
4  Jhanvi   28  Chennai  65000  IT

#### isin() method

In [48]:
df[df["city"].isin(["Delhi","Banglore"])]

    Name  age      city    sal Dep
0  Rahul   25  Banglore  78000  IT

In [50]:
df[df["Dep"].isin(["IT","Finance"])]

     Name  age      city    sal      Dep
0   Rahul   25  Banglore  78000       IT
2   Kumar   44   Kolkata  45000  Finance
4  Jhanvi   28   Chennai  65000       IT
5   Arjun   45     Dehli  50000  Finance

#### between()

In [51]:
df[df["age"].between(30,50)]

    Name  age     city    sal      Dep
1    Joy   35     Pune  25000       HR
2  Kumar   44  Kolkata  45000  Finance
5  Arjun   45    Dehli  50000  Finance

#### sorting + EDA

In [55]:
#sort_values() this is the func to sort the data/things
#it has multiple parameters

df.sort_values("sal",ascending=False)

     Name  age      city    sal      Dep
0   Rahul   25  Banglore  78000       IT
4  Jhanvi   28   Chennai  65000       IT
5   Arjun   45     Dehli  50000  Finance
2   Kumar   44   Kolkata  45000  Finance
1     Joy   35      Pune  25000       HR
3    Mahi   21    Mumbai  12000       HR

In [56]:
df.sort_values(["Dep","sal"])

     Name  age      city    sal      Dep
2   Kumar   44   Kolkata  45000  Finance
5   Arjun   45     Dehli  50000  Finance
3    Mahi   21    Mumbai  12000       HR
1     Joy   35      Pune  25000       HR
4  Jhanvi   28   Chennai  65000       IT
0   Rahul   25  Banglore  78000       IT